alter table lab1_api_stadium add primary key(id);
alter table lab1_api_stadium add search tsvector generated always as(to_tsvector('simple', name)) stored;
create index stadium_search_idx on lab1_api_stadium using gin(search);
create index lab1_api_stadium_user_idx on lab1_api_stadium (user_id);
alter table lab1_api_competition add primary key(id);
alter table lab1_api_competition add search tsvector generated always as(to_tsvector('simple', name)) stored;
create index competition_search_idx on lab1_api_competition using gin(search);
create index lab1_api_competition_user_idx on lab1_api_competition (user_id);
alter table lab1_api_club add primary key(id);
alter table lab1_api_club add search tsvector generated always as(to_tsvector('simple', name)) stored;
create index club_search_idx on lab1_api_club using gin(search);
create index lab1_api_club_league_idx on lab1_api_club (league_id);
create index lab1_api_club_stadium_idx on lab1_api_club (stadium_id);
create index lab1_api_club_user_idx on lab1_api_club (user_id);
alter table lab1_api_matchesplayed add primary key(id);
create index lab1_api_matchesplayed_stadium_idx on lab1_api_matchesplayed (stadium_id);
create index lab1_api_matchesplayed_club1_idx on lab1_api_matchesplayed (club1_id);
create index lab1_api_matchesplayed_competition_idx on lab1_api_matchesplayed (competition_id);
create index lab1_api_matchesplayed_user_idx on lab1_api_matchesplayed (user_id);
