# Generated by Django 4.1.7 on 2023-03-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numberOfClubs', models.IntegerField()),
                ('numberOfTrophies', models.IntegerField()),
                ('foundedDate', models.DateField()),
                ('relegationNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('annualBudget', models.IntegerField()),
                ('numberOfStadd', models.IntegerField()),
                ('foundedDate', models.DateField()),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab1_api.league')),
                ('stadium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab1_api.stadium')),
            ],
        ),
    ]
