# Generated by Django 4.1.7 on 2023-05-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_api', '0002_alter_user_confirmation_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='marital',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('R', 'Relationship'), ('S', 'Single')], max_length=2, null=True),
        ),
    ]
