# Generated by Django 4.1.7 on 2023-03-15 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_api', '0002_league_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MatchesPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundOfPlay', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('club1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_club1', to='lab1_api.club')),
                ('club2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_club2', to='lab1_api.club')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab1_api.competition')),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab1_api.competition'),
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
