# Generated by Django 4.1.7 on 2023-03-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_api', '0003_competition_matchesplayed_alter_club_league_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='league',
        ),
        migrations.RemoveField(
            model_name='matchesplayed',
            name='competition',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
