# Generated by Django 4.1.7 on 2023-05-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_api', '0003_alter_userdetail_bio_alter_userdetail_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='marital',
            field=models.CharField(choices=[('M', 'Married'), ('R', 'Relationship'), ('S', 'Single')], max_length=2, null=True),
        ),
    ]
