# Generated by Django 4.1.7 on 2023-05-02 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_api', '0004_alter_user_confirmation_code_alter_userdetail_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='userName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
