# Generated by Django 4.1.7 on 2023-03-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_api', '0004_remove_club_league_remove_matchesplayed_competition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('foundedDate', models.DateField()),
                ('competitionType', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab1_api.competition'),
        ),
        migrations.AddField(
            model_name='matchesplayed',
            name='competition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lab1_api.competition'),
            preserve_default=False,
        ),
    ]
