# Generated by Django 4.1.7 on 2023-03-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_api', '0005_competition_club_league_matchesplayed_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchesplayed',
            name='stadium',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lab1_api.stadium'),
            preserve_default=False,
        ),
    ]
