# Generated by Django 4.1.7 on 2023-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_api', '0006_matchesplayed_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='numberOfTeams',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='prizeMoney',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
