# Generated by Django 4.1.7 on 2023-05-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_api', '0007_alter_club_user_alter_competition_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Moderator', 'Moderator'), ('Admin', 'Admin')], default='Regular', max_length=30),
        ),
    ]
