# Generated by Django 4.1.7 on 2023-04-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1_api', '0007_competition_numberofteams_competition_prizemoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
