version: '3.8'

services:
  web:
    build: 
      context: .
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_user_123
      - POSTGRES_DB=leaguelizer

volumes:
  postgres_data: